version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/fullchain.pem:/usr/local/etc/haproxy/cert.pem:ro
      - ./haproxy/key.pem:/usr/local/etc/haproxy/key.pem:ro
   # depends_on:
   #   - apache
      #- python

  apache:
    image: httpd:latest
    volumes:
      - ./apache:/usr/local/apache2/htdocs

  #python:
  #  build: ./python
  #  ports:
  #    - "5000:5000"