version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/fullchain.pem:/usr/local/etc/haproxy/cert.pem:ro
      - ./haproxy/key.pem:/usr/local/etc/haproxy/key.pem:ro
   # depends_on:
   #   - apache
      #- python

  apache:
    image: httpd:latest
    # para que puedan probar en el puerto 9090
    ports:
      - "9090:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs

  python:
    build: ./python
    volumes:
      - ./python:/app
    ports:
      - "8501:8501"